fix: incorrect ecs:ListTasks permission (#1207)
The ECS task monitor lambda fails on the following error:

```
AccessDeniedException: User: arn:aws:sts::573688003310:assumed-role/<...> is not authorized to perform: ecs:ListTasks on resource: * because no identity-based policy allows the ecs:ListTasks action
```

This is because the `ecs:ListTasks` action may only be scoped by `container-instance`, and we're listing across all container instances in the main cluster, so the `Resource` being authorized for is `*`, and the `ecs:cluster` condition provides the necessary scoping down.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*